{{- if .Values.clusterSecret.enabled }}
kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
matchNamespace:
  {{- .Values.clusterSecret.namespaces | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  valueFrom:
    secretKeyRef:
      name: {{ include "chart.fullname" . }}
{{- end }}
