name: Docker Image CI

on:
  push:
    tags:
    - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        tags: |
          ghcr.io/schub-cloud/image-pull-secret-injector:latest
          ghcr.io/schub-cloud/image-pull-secret-injector:${{ github.ref_name }}
        push: true
        cache-from: type=registry,ref=ghcr.io/schub-cloud/image-pull-secret-injector:buildcache
        cache-to: type=registry,ref=ghcr.io/schub-cloud/image-pull-secret-injector:buildcache,mode=max
